spring:
  redis:
    database: 0
    host: 192.168.137.129
    port: 6379
    timeout: 10000
    jedis:
      pool:
        # 最大活跃连接数，负数为不限制
        max-active: -1
        # 等待可用连接的最大时间，负数为不限制
        max-wait:  -1s
        # 最大空闲连接数
        max-idle: 500
        # 最小空闲连接数
        min-idle: 50

